# Generated by Django 4.2.4 on 2024-03-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_category_alter_card_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='логотип')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
