# Generated by Django 4.2.4 on 2024-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ManyToManyField(to='flower.card', verbose_name='Цветы'),
        ),
    ]
