# Generated by Django 4.2.4 on 2024-03-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_remove_order_card_order_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.CreateModel(
            name='FlowerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_flower', to='flower.card', verbose_name='Цветы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_order', to='flower.order', verbose_name='Заказ')),
            ],
        ),
    ]
